### ISSUE TITLE
Doesn't work as compile dependency

### ISSUE THREAD

**Issue by mgroth0** [DevinTDHa/precompiled-tf-jni-m1#1]
@DevinTDHa , I tried your jars and am having issues. First I tried including them as a Gradle dependency, and they didn't work. I got `Unresolved reference: tensorflow`. Next I tried checking my Gradle `--debug` info, and confirmed that each of your jars are in fact in my compile class path. Finally I decided to look inside the jars to, but could not do so. Running `jar -tf` on any of your jars gives me
```
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
	at jdk.jartool/sun.tools.jar.Main.list(Main.java:1484)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:352)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1665)
```

**Comment by DevinTDHa** [comment]
I didn't mention it before (updated now) but the files were uploaded with git lfs. 

Try running `git lfs pull` to get the files beforehand (or download it directly here on github).

**Comment by mgroth0** [comment]
I downloaded the jars manually and that fixed this issue, thanks.
